apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: demo
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - name: postgres-std
          containerPort: 5432 
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust