apiVersion: v1
kind: Pod
metadata:
  name: result-app
  namespace: demo
  labels:
    role: result
    app: result-app
spec:
  containers:
    - name: result-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - name: http-standard
          containerPort: 80
          protocol: TCP