apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-rw
  namespace: lab
  labels:
    app: flask
spec:
  storageClassName: flask-rw
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
