apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-rw
  labels:
    app: flask
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
