apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-rw
  labels:
    app: flask
spec:
  storageClassName: local-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
