apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: k8s--lab-m1.ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  cidr: 10.50.0.0/24
  blockSize: 24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: "kubernetes.io/hostname == 'k8s-master-1.lab.local'"
  vxlanMode: Never
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: k8s-lab-w1.ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  cidr: 10.50.1.0/24
  blockSize: 24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: "kubernetes.io/hostname == 'k8s-worker-1.lab.local'"
  vxlanMode: Never
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: k8s-lab-w2.ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  cidr: 10.50.2.0/24
  blockSize: 24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: "kubernetes.io/hostname == 'k8s-worker-2.lab.local'"
  vxlanMode: Never
