apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-flask
  labels:
    app: simple-flask
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
