apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-dev-data
  namespace: keycloak
  labels:
    app: kc-dev-mysql
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
