apiVersion: v1
kind: Pod
metadata:
  name: web-blue
  namespace: lab
  labels:
    group: nginxweblb
spec:
  hostname: webblue-k8s
  subdomain: nginxweblb
  containers:
    - name: web-blue
      image: docker.io/fureasu346/nginx:web_blue
      ports: 
        - containerPort: 80
          protocol: TCP
          hostPort: 7002
          
      