apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mmrcis-mssql-data
  labels:
    app: mmrcis-mssql-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
