apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
    name: testinnodbcluster
    namespace: lab
spec:
  secretName: innodbpwds
  serviceAccountName: innodb-sa
  tlsUseSelfSigned: true
  instances: 3
  router:
  instances: 1
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    storageClassName: mysql
    resources:
      requests:
        storage: 100Gi
