apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sidecar-namespace-list
  namespace: innodb
subjects:
  - kind: ServiceAccount
    name: mycluster-sidecar-sa
    namespace: innodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-namespaces 
