apiVersion: v1 
kind: Service
metadata:
  name: web-service
  namespace: website
spec:
  type: NodePort
  ports:
    - name: 30008-http-standard
      port: 80 
      targetPort: http-standard
      nodePort: 30008
      protocol: TCP
  selector:
    role: frontend
    service: web