apiVersion: v1 
kind: Service
metadata:
  name: db-service
  namespace: website
spec:
  type: ClusterIP
  ports:
      - targetPort: mysql-standard
        port: 3306
        protocol: TCP
  selector:
    role: backend
    service: db