apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-artifact
  namespace: wso2
  labels:
    app: wso2am
spec:
  storageClassName: wso2am
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi