apiVersion: v1
kind: Service
metadata:
  name: simple-web
  namespace: lab 
  labels:
    role: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http-standard
      nodePort: 30008
  externalIPs:
    - 192.168.52.11
    - 192.168.52.12
    - 192.168.52.13
  selector:
    role: frontend
    app: web-apache-php