apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  iops: "3000"        
  throughput: "125"  
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer