apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: devmq
    namespace: dev
spec:
    replicas: 2
    service:
      type: LoadBalancer
    persistence:
      storageClassName: rabbitmq
      storage: 1G
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 1Gi 