apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: devmq
    namespace: dev
spec:
    replicas: 2
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-name: "dev-mq-eks-intsmm-net"
    persistence:
      storageClassName: gp2
      storage: 1G
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 1Gi 