apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.20.0.3
  share: /exports/rabbitmq
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
- nfsvers=4.1
