apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.20.203.41
  share: /mnt/Storage_Pool/k8s/rabbitmq
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
- nfsvers=4.1
