apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-postgres
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wso2am
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /mnt/Storage_Pool/k8s/wso2/wso2am-postgres
    server: 172.20.203.41
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-data
  namespace: wso2
  labels:
    app: wso2am
spec:
  storageClassName: wso2am
  volumeName: wso2am-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi