apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wso2am
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.20.0.3
  share: /exports/wso2am
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1