apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: kc-test
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: mysql
    host: innodb.innodb
    usernameSecret:
      name: kc-dev-db
      key: username
    passwordSecret:
      name: kc-dev-db
      key: password
  http:
    tlsSecret: kc-dev-tls
  hostname:
    hostname: kc-dev.k8s.intsmm.net
  proxy:
    headers: xforwarded
  ingress:
    enabled: true
  #additionalOptions:
    #- name: proxy
      #value: reencrypt
