FROM wso2/wso2am:4.4.0-rocky

ENV TZ=Asia/Yangon

COPY postgresql-42.7.5.jar /home/wso2carbon/wso2am-4.4.0/repository/components/lib/
COPY mysql-connector-j-9.2.0.jar /home/wso2carbon/wso2am-4.4.0/repository/components/lib
COPY deployment.toml /home/wso2carbon/wso2am-4.4.0/repository/conf/