apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.64.1
  share: /share
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
