apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.20.0.3
  share: /exports/k8s-mysql
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
