apiVersion: v1
kind: Pod
metadata:
  name: test-flask
  namespace: default
  labels:
    app: test-flask
spec:
  containers:
  - name: test-flask
    image: fureasu346/flask:rw
    ports:
      - containerPort: 8765
        protocol: TCP
        hostPort: 30008
    volumeMounts:
      - name: data
        mountPath: /app/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pv-claim