apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo
  labels:
    role: backend
    name: redis-for-vote
spec:
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
  selector:
    role: vote
    app: redis
