apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: demo
  labels:
    role: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-standard
  selector:
    role: result
    app: result-app