apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: demo
  labels:
    role: frontend
spec:
  type: ClusterIP
  ports:
    - name: http-vote
      port: 80
      targetPort: 80
  selector:
    role: vote
    app: voting-app