apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: demo
  labels:
    role: backend
    name: postgres-for-result
spec:
  ports:
    - port: 5432
      targetPort: postgres-std
  selector:
    role: result
    app: postgres
