apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: demo
  labels:
    role: backend
    name: postgres-for-result
spec:
  ports:
    - name: tcp-postgres
      port: 5432
      targetPort: 5432
  selector:
    role: result
    app: postgres
