apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: demo
  labels:
    role: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-standard
  selector:
    role: vote
    app: voting-app