apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: demo
  labels:
    role: frontend
spec:
  type: ClusterIP
  ports:
    - name: http-result
      port: 80
      targetPort: 80
  selector:
    role: result
    app: result-app