apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: demo
  labels:
    role: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http-standard
      nodePort: 30002
  externalIPs:
    - 192.168.52.12
    - 192.168.52.13
  selector:
    role: result
    app: result-app