apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: demo
  labels:
    role: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http-standard
      nodePort: 30001
  externalIPs:
    - 192.168.52.12
    - 192.168.52.13
  selector:
    role: vote
    app: voting-app