apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
  namespace: lab
spec:
  selector:
    matchLabels:
      role: frontend
      app: web-apache-php
  revisionHistoryLimit: 5
  replicas: 3
  template:
    metadata:
      name: simpleweb
      namespace: lab
      labels:
        role: frontend
        app: web-apache-php
    spec:
      containers:
        - name: simpleweb
          image: fureasu346/simplewebdb_webapachephp:v1
          env:
          - name: DB_SERVERNAME
            value: "simple-db.lab.svc.cluster.local"
          - name: DB_NAME
            value: "testdb"
          - name: DB_USERNAME
            value: "webserver"
          - name: DB_PASSWORD
            value: "webserverP@ssw0rd"
          - name: WEBSITE_NAME
            value: "simplewebdb.lab"
          ports:
            - name: http-standard
              containerPort: 80
              protocol: TCP