apiVersion: v1
kind: Pod
metadata:
  name: redis-db
  namespace: default
  labels:
    app: my_redis
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP