apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: lab
  labels:
    app: test-nginx
spec:
  containers:
  - name: test-nginx
    image: fureasu346/nginx:web
    ports:
      - containerPort: 80
        protocol: TCP
        hostPort: 30008
    volumeMounts:
      - name: index
        mountPath: /var/www/html
  volumes:
    - name: index
      configMap:
        name: test-nginx
        items:
          - key: index
            path: index.php